version: "3.9"

services:
  backend:
    container_name: backend
    build: ./
    command: bash -c "npm run dev"
    ports:
      - 3001:3001
    env_file:
      - ./.env
    volumes:
      - .:/usr/app