name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0